/**
 * SSE fixtures: Multi-tool exploration flow
 * "在项目文件中找到最核心的那句话"
 *
 * Round 1: Model calls "grep" to search for the key phrase
 * Round 2: Model calls "read" to read the file containing the phrase
 * Round 3: Model responds with what it found
 *
 * Confirmation text generated by gemini-3-flash LLM.
 */

const CONFIRMATION_TEXT =
    '我已经为您在项目文件的 `src/core/secret.ts` 中找到了最核心的那句话。这句话的内容是 \\"AnyCode: 让编程发生在任何地方\\"。'

/**
 * Build SSE fixtures for the multi-tool exploration test.
 * filePath must be relative (resolved by tools against Instance.directory).
 */
export function buildExplorationFixtures() {
    // ── Round 1: grep tool call ───────────────────────────────────────────
    const grepArgs = JSON.stringify({ pattern: "让编程发生" })
    const grepEscaped = JSON.stringify(grepArgs).slice(1, -1)

    const grepBody = [
        `data: {"type":"response.created","response":{"id":"resp_exp001","object":"response","created_at":1700000000,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"function_call","id":"fc_grep01","call_id":"call_grep_01","name":"grep","arguments":"","status":"in_progress"}}\n\n`,
        `data: {"type":"response.function_call_arguments.delta","output_index":0,"item_id":"fc_grep01","delta":"${grepEscaped}"}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"function_call","id":"fc_grep01","call_id":"call_grep_01","name":"grep","arguments":"${grepEscaped}","status":"completed"}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_exp001","object":"response","created_at":1700000000,"model":"gpt-4o","status":"completed","output":[{"type":"function_call","id":"fc_grep01","call_id":"call_grep_01","name":"grep","arguments":"${grepEscaped}","status":"completed"}],"usage":{"input_tokens":150,"output_tokens":30,"total_tokens":180,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    // ── Round 2: read tool call ───────────────────────────────────────────
    const readArgs = JSON.stringify({ filePath: "src/core/secret.ts" })
    const readEscaped = JSON.stringify(readArgs).slice(1, -1)

    const readBody = [
        `data: {"type":"response.created","response":{"id":"resp_exp002","object":"response","created_at":1700000001,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"function_call","id":"fc_read01","call_id":"call_read_01","name":"read","arguments":"","status":"in_progress"}}\n\n`,
        `data: {"type":"response.function_call_arguments.delta","output_index":0,"item_id":"fc_read01","delta":"${readEscaped}"}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"function_call","id":"fc_read01","call_id":"call_read_01","name":"read","arguments":"${readEscaped}","status":"completed"}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_exp002","object":"response","created_at":1700000001,"model":"gpt-4o","status":"completed","output":[{"type":"function_call","id":"fc_read01","call_id":"call_read_01","name":"read","arguments":"${readEscaped}","status":"completed"}],"usage":{"input_tokens":250,"output_tokens":20,"total_tokens":270,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    // ── Round 3: Confirmation text ────────────────────────────────────────
    const confirmationBody = [
        `data: {"type":"response.created","response":{"id":"resp_exp003","object":"response","created_at":1700000002,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"message","id":"msg_exp003","role":"assistant","content":[]}}\n\n`,
        `data: {"type":"response.content_part.added","output_index":0,"content_index":0,"part":{"type":"output_text","text":""}}\n\n`,
        `data: {"type":"response.output_text.delta","output_index":0,"content_index":0,"item_id":"msg_exp003","delta":"${CONFIRMATION_TEXT}"}\n\n`,
        `data: {"type":"response.output_text.done","output_index":0,"content_index":0,"text":"${CONFIRMATION_TEXT}"}\n\n`,
        `data: {"type":"response.content_part.done","output_index":0,"content_index":0,"part":{"type":"output_text","text":"${CONFIRMATION_TEXT}"}}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"message","id":"msg_exp003","role":"assistant","content":[{"type":"output_text","text":"${CONFIRMATION_TEXT}"}]}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_exp003","object":"response","created_at":1700000002,"model":"gpt-4o","status":"completed","output":[{"type":"message","id":"msg_exp003","role":"assistant","content":[{"type":"output_text","text":"${CONFIRMATION_TEXT}"}]}],"usage":{"input_tokens":400,"output_tokens":40,"total_tokens":440,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    return { grepBody, readBody, confirmationBody }
}
