/**
 * SSE fixtures: "创建一个 hello world 的 HTML 页面" flow
 * OpenAI Responses API format (/v1/responses)
 *
 * Round 1: Model calls the "write" tool to create index.html
 * Round 2: After tool result, model responds with confirmation text
 *
 * HTML content and confirmation text generated by gemini-3-flash LLM.
 */

export const HTML_CONTENT = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>Welcome to your first HTML page. This is a simple and clean "Hello World" example.</p>
</body>
</html>`

/**
 * Build SSE fixtures dynamically so the filePath can be set to an absolute path
 * that points into the test's temp directory (WriteTool requires absolute paths
 * or resolves relative paths against Instance.directory).
 */
export function buildHelloworldFixtures(filePath = "index.html") {
    const args = JSON.stringify({ filePath, content: HTML_CONTENT })
    // Double-escape for embedding inside SSE JSON string values
    const escaped = JSON.stringify(args).slice(1, -1)

    const CONFIRMATION_TEXT =
        "我已经为您创建了 index.html 文件。这是一个结构完整的 HTML5 页面。"

    // ── Round 1: Model calls "write" tool ─────────────────────────────────
    const toolCallBody = [
        `data: {"type":"response.created","response":{"id":"resp_hw001","object":"response","created_at":1700000000,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"function_call","id":"fc_hw001","call_id":"call_write_hw","name":"write","arguments":"","status":"in_progress"}}\n\n`,
        `data: {"type":"response.function_call_arguments.delta","output_index":0,"item_id":"fc_hw001","delta":"${escaped}"}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"function_call","id":"fc_hw001","call_id":"call_write_hw","name":"write","arguments":"${escaped}","status":"completed"}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_hw001","object":"response","created_at":1700000000,"model":"gpt-4o","status":"completed","output":[{"type":"function_call","id":"fc_hw001","call_id":"call_write_hw","name":"write","arguments":"${escaped}","status":"completed"}],"usage":{"input_tokens":120,"output_tokens":45,"total_tokens":165,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    // ── Round 2: Confirmation text ────────────────────────────────────────
    const confirmationBody = [
        `data: {"type":"response.created","response":{"id":"resp_hw002","object":"response","created_at":1700000001,"model":"gpt-4o","status":"in_progress","output":[]}}\n\n`,
        `data: {"type":"response.output_item.added","output_index":0,"item":{"type":"message","id":"msg_hw002","role":"assistant","content":[]}}\n\n`,
        `data: {"type":"response.content_part.added","output_index":0,"content_index":0,"part":{"type":"output_text","text":""}}\n\n`,
        `data: {"type":"response.output_text.delta","output_index":0,"content_index":0,"item_id":"msg_hw002","delta":"${CONFIRMATION_TEXT}"}\n\n`,
        `data: {"type":"response.output_text.done","output_index":0,"content_index":0,"text":"${CONFIRMATION_TEXT}"}\n\n`,
        `data: {"type":"response.content_part.done","output_index":0,"content_index":0,"part":{"type":"output_text","text":"${CONFIRMATION_TEXT}"}}\n\n`,
        `data: {"type":"response.output_item.done","output_index":0,"item":{"type":"message","id":"msg_hw002","role":"assistant","content":[{"type":"output_text","text":"${CONFIRMATION_TEXT}"}]}}\n\n`,
        `data: {"type":"response.completed","response":{"id":"resp_hw002","object":"response","created_at":1700000001,"model":"gpt-4o","status":"completed","output":[{"type":"message","id":"msg_hw002","role":"assistant","content":[{"type":"output_text","text":"${CONFIRMATION_TEXT}"}]}],"usage":{"input_tokens":200,"output_tokens":25,"total_tokens":225,"output_tokens_details":{"reasoning_tokens":0},"input_tokens_details":{"cached_tokens":0}}}}\n\n`,
    ].join("")

    return { toolCallBody, confirmationBody }
}
