import { testPaths, testNodeDeps } from "./_test-paths"
/**
 * Test: Context compaction (上下文压缩)
 *
 * Verifies that the agent triggers context compaction when token usage
 * exceeds the model's context limit, and continues the conversation
 * after producing a summary.
 *
 * Flow:
 *   1. Initial response with very high token usage → triggers compaction
 *   2. Compaction agent summarizes the conversation
 *   3. Agent continues with a fresh response after compaction
 *
 * Mock SSE messages generated by gemini-3-flash via the user's LLM endpoint.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from "vitest"
import { http, HttpResponse } from "msw"
import { CodeAgent, NodeFS, NodeSearchProvider } from "../src/index"
import { createTempDir, cleanupTempDir, server } from "./setup"
import {
    buildCompactionFixtures,
    INITIAL_RESPONSE,
    CONTINUATION_RESPONSE,
} from "./fixtures/compaction-stream"
import { RESPONSES_API_BODY } from "./fixtures/text-stream"
import { SqlJsStorage } from "../src/storage-sqljs"

describe("CodeAgent: context compaction", () => {
    let agent: CodeAgent
    let tmpDir: string

    beforeAll(async () => {
        tmpDir = createTempDir()

        agent = new CodeAgent({
            ...testNodeDeps(),
            storage: new SqlJsStorage(),
            directory: tmpDir,
            fs: new NodeFS(),
            search: new NodeSearchProvider(),
            dataPath: testPaths(),
            provider: {
                id: "openai",
                apiKey: "test-key-not-real",
                model: "gpt-4o",
                baseUrl: "http://localhost:19283/v1",
            },
        })

        await agent.init()
    }, 60_000)

    afterAll(() => {
        cleanupTempDir(tmpDir)
    })

    beforeEach(() => {
        let mainCallCount = 0
        const { initialBody, compactionBody, continuationBody } =
            buildCompactionFixtures()

        server.use(
            http.post("*/v1/responses", async ({ request }) => {
                const body = (await request
                    .clone()
                    .json()
                    .catch(() => ({}))) as Record<string, unknown>
                const model = (body?.model ?? "") as string

                // Background models (title, summary) get generic response
                if (model !== "gpt-4o") {
                    return new HttpResponse(RESPONSES_API_BODY, {
                        headers: {
                            "Content-Type": "text/event-stream",
                            "Cache-Control": "no-cache",
                            Connection: "keep-alive",
                        },
                    })
                }

                mainCallCount++
                // Round 1: initial (high tokens) → triggers compaction
                // Round 2: compaction summary
                // Round 3+: continuation
                let responseBody: string
                if (mainCallCount === 1) responseBody = initialBody
                else if (mainCallCount === 2) responseBody = compactionBody
                else responseBody = continuationBody

                return new HttpResponse(responseBody, {
                    headers: {
                        "Content-Type": "text/event-stream",
                        "Cache-Control": "no-cache",
                        Connection: "keep-alive",
                    },
                })
            }),
        )
    })

    it("should trigger compaction and continue conversation after summary", async () => {
        const session = await agent.createSession()
        const events: Array<{
            type: string
            content?: string
            error?: string
        }> = []

        for await (const event of agent.chat(
            session.id,
            "你好，帮我分析一下这个项目的架构",
        )) {
            events.push(event)
        }

        // Should end with done
        const lastEvent = events[events.length - 1]
        expect(lastEvent.type).toBe("done")

        // ── Collect all text deltas ───────────────────────────────────────
        let fullText = ""
        for (const event of events) {
            if (event.type === "text.delta" && event.content) {
                fullText += event.content
            }
        }

        // Should contain the initial response text
        expect(fullText).toContain("分析")

        // Should contain the continuation response
        // (this proves compaction happened and conversation continued)
        expect(fullText).toContain("继续")

        // Should not have error events (compaction is a normal flow)
        const errors = events.filter((e) => e.type === "error")
        expect(errors.length).toBe(0)

        // The text should contain content from multiple rounds,
        // indicating the agent didn't stop after the first response
        const textEvents = events.filter((e) => e.type === "text.delta")
        expect(textEvents.length).toBeGreaterThanOrEqual(2)
    }, 120_000)
})
