/**
 * Test: Multi-tool exploration — find the core phrase
 *
 * Sets up a small project with files, one containing a hidden key phrase.
 * The agent uses grep → read tools to locate and read it, then confirms.
 *
 * Mock SSE messages generated by gemini-3-flash via the user's LLM endpoint.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from "vitest"
import { http, HttpResponse } from "msw"
import fs from "fs"
import path from "path"
import { CodeAgent } from "../src/index"
import { createTempDir, cleanupTempDir, server } from "./setup"
import { buildExplorationFixtures } from "./fixtures/exploration-stream"
import { RESPONSES_API_BODY } from "./fixtures/text-stream"

/**
 * The secret key phrase hidden in the project files.
 */
const SECRET_PHRASE = "AnyCode: 让编程发生在任何地方"

describe("CodeAgent: multi-tool exploration", () => {
    let agent: CodeAgent
    let tmpDir: string

    beforeAll(async () => {
        tmpDir = createTempDir()

        // ── Create project files ──────────────────────────────────────────
        // Normal files (distractors)
        fs.mkdirSync(path.join(tmpDir, "src", "utils"), { recursive: true })
        fs.mkdirSync(path.join(tmpDir, "src", "core"), { recursive: true })
        fs.mkdirSync(path.join(tmpDir, "docs"), { recursive: true })

        fs.writeFileSync(
            path.join(tmpDir, "src", "config.ts"),
            `export const config = {\n  port: 3000,\n  host: "localhost",\n}\n`,
        )
        fs.writeFileSync(
            path.join(tmpDir, "src", "utils", "helpers.ts"),
            `export function formatDate(d: Date) {\n  return d.toISOString()\n}\n`,
        )
        fs.writeFileSync(
            path.join(tmpDir, "docs", "README.md"),
            `# Project\n\nThis is a sample project for testing.\n`,
        )

        // The file with the secret key phrase
        fs.writeFileSync(
            path.join(tmpDir, "src", "core", "secret.ts"),
            [
                `/**`,
                ` * Core module`,
                ` *`,
                ` * This file contains the project's core philosophy.`,
                ` */`,
                ``,
                `// ${SECRET_PHRASE}`,
                `export const CORE_MISSION = "${SECRET_PHRASE}"`,
                ``,
                `export function getCoreMessage(): string {`,
                `  return CORE_MISSION`,
                `}`,
                ``,
            ].join("\n"),
        )

        // ── Init agent ────────────────────────────────────────────────────
        agent = new CodeAgent({
            directory: tmpDir,
            skipPlugins: true,
            provider: {
                id: "openai",
                apiKey: "test-key-not-real",
                model: "gpt-4o",
                baseUrl: "http://localhost:19283/v1",
            },
        })

        await agent.init()
    }, 60_000)

    afterAll(() => {
        cleanupTempDir(tmpDir)
    })

    beforeEach(() => {
        let mainCallCount = 0
        const { grepBody, readBody, confirmationBody } =
            buildExplorationFixtures()

        server.use(
            http.post("*/v1/responses", async ({ request }) => {
                const body = (await request
                    .clone()
                    .json()
                    .catch(() => ({}))) as Record<string, unknown>
                const model = (body?.model ?? "") as string

                // Background models get generic response
                if (model !== "gpt-4o") {
                    return new HttpResponse(RESPONSES_API_BODY, {
                        headers: {
                            "Content-Type": "text/event-stream",
                            "Cache-Control": "no-cache",
                            Connection: "keep-alive",
                        },
                    })
                }

                mainCallCount++
                // Round 1: grep, Round 2: read, Round 3+: confirmation
                let responseBody: string
                if (mainCallCount === 1) responseBody = grepBody
                else if (mainCallCount === 2) responseBody = readBody
                else responseBody = confirmationBody

                return new HttpResponse(responseBody, {
                    headers: {
                        "Content-Type": "text/event-stream",
                        "Cache-Control": "no-cache",
                        Connection: "keep-alive",
                    },
                })
            }),
        )
    })

    it("should use grep and read tools to find the secret phrase", async () => {
        const session = await agent.createSession()
        const events: Array<{
            type: string
            content?: string
            toolName?: string
            toolOutput?: string
            error?: string
        }> = []

        for await (const event of agent.chat(
            session.id,
            "在项目文件中找到最核心的那句话",
        )) {
            events.push(event)
        }

        // Should end with done
        const lastEvent = events[events.length - 1]
        expect(lastEvent.type).toBe("done")

        // ── Verify tool calls ─────────────────────────────────────────────
        const toolStarts = events.filter((e) => e.type === "tool_call_start")
        const toolNames = toolStarts.map((e) => e.toolName)

        // Should have called grep and read (in that order)
        expect(toolNames).toContain("grep")
        expect(toolNames).toContain("read")
        expect(toolNames.indexOf("grep")).toBeLessThan(
            toolNames.indexOf("read"),
        )

        // ── Verify grep found the file ────────────────────────────────────
        const grepDone = events.find(
            (e) => e.type === "tool_call_done" && e.toolName === "grep",
        )
        expect(grepDone).toBeDefined()
        expect(grepDone!.toolOutput).toContain("secret.ts")

        // ── Verify read got the content ───────────────────────────────────
        const readDone = events.find(
            (e) => e.type === "tool_call_done" && e.toolName === "read",
        )
        expect(readDone).toBeDefined()
        expect(readDone!.toolOutput).toContain(SECRET_PHRASE)

        // ── Verify confirmation text ──────────────────────────────────────
        let fullText = ""
        for (const event of events) {
            if (event.type === "text_delta" && event.content) {
                fullText += event.content
            }
        }
        expect(fullText).toContain("secret.ts")
        expect(fullText).toContain("让编程发生在任何地方")
    })
})
