import { testPaths, testNodeDeps } from "./_test-paths"
/**
 * Test: Create a Hello World HTML page
 *
 * Verifies that CodeAgent correctly handles a "创建一个 hello world 的 HTML 页面"
 * request — the LLM calls the "write" tool to create index.html, then responds
 * with a confirmation message.
 *
 * Mock SSE messages generated by gemini-3-flash via the user's LLM endpoint.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from "vitest"
import { http, HttpResponse } from "msw"
import path from "path"
import { CodeAgent } from "../src/index"
import { createTempDir, cleanupTempDir, server } from "./setup"
import {
    buildHelloworldFixtures,
    HTML_CONTENT,
} from "./fixtures/helloworld-html-stream"
import { RESPONSES_API_BODY } from "./fixtures/text-stream"
import { InMemoryFS } from "./fixtures/in-memory-fs"
import { SqlJsStorage } from "../src/storage-sqljs"
import { InMemorySearchProvider } from "./fixtures/search-memory"

describe("CodeAgent: create hello world HTML page", () => {
    let agent: CodeAgent
    let tmpDir: string
    let memFS: InMemoryFS

    beforeAll(async () => {
        tmpDir = createTempDir()
        memFS = new InMemoryFS()

        agent = new CodeAgent({
            ...testNodeDeps(),
            storage: new SqlJsStorage(),
            directory: tmpDir,
            fs: memFS,
            search: new InMemorySearchProvider(new InMemoryFS()),
            dataPath: testPaths(),
            provider: {
                id: "openai",
                apiKey: "test-key-not-real",
                model: "gpt-4o",
                baseUrl: "http://localhost:19283/v1",
            },
        })

        await agent.init()
    }, 60_000)

    afterAll(() => {
        cleanupTempDir(tmpDir)
    })

    // Install the hello-world mock handler before each test.
    // We need to handle the main chat model (gpt-4o) separately from
    // background models (title, summary etc.) which also call /v1/responses.
    beforeEach(() => {
        // Track calls only for the main chat model (gpt-4o)
        let mainCallCount = 0
        // Use relative path — WriteTool resolves it against Instance.directory.
        // Avoids external_directory permission check (macOS /var vs /private/var
        // symlink causes Instance.containsPath() to fail with absolute tmpDir paths)
        const { toolCallBody, confirmationBody } =
            buildHelloworldFixtures("index.html")

        server.use(
            http.post("*/v1/responses", async ({ request }) => {
                const body = (await request.clone().json().catch(() => ({}))) as Record<string, unknown>
                const model = (body?.model ?? "") as string

                // For background models (title, summary etc.), return a
                // generic text response so they don't interfere
                if (model !== "gpt-4o") {
                    return new HttpResponse(RESPONSES_API_BODY, {
                        headers: {
                            "Content-Type": "text/event-stream",
                            "Cache-Control": "no-cache",
                            Connection: "keep-alive",
                        },
                    })
                }

                // Main chat model
                mainCallCount++
                const responseBody =
                    mainCallCount === 1 ? toolCallBody : confirmationBody
                return new HttpResponse(responseBody, {
                    headers: {
                        "Content-Type": "text/event-stream",
                        "Cache-Control": "no-cache",
                        Connection: "keep-alive",
                    },
                })
            }),
        )
    })

    it("should create index.html via the write tool and stream confirmation", async () => {
        const session = await agent.createSession()
        const events: Array<{
            type: string
            content?: string
            toolName?: string
            error?: string
        }> = []

        for await (const event of agent.chat(
            session.id,
            "创建一个 hello world 的 HTML 页面",
        )) {
            events.push(event)
        }

        // Should have received events and ended with done
        expect(events.length).toBeGreaterThan(0)
        const lastEvent = events[events.length - 1]
        expect(lastEvent.type).toBe("done")

        // Should have tool_call_start and tool_call_done events for the "write" tool
        const toolStarts = events.filter((e) => e.type === "tool_call_start")
        expect(toolStarts.length).toBeGreaterThan(0)
        expect(toolStarts[0].toolName).toBe("write")

        const toolDones = events.filter((e) => e.type === "tool_call_done")
        expect(toolDones.length).toBeGreaterThan(0)

        // ── Verify the file was written through the VFS ──
        const writtenPaths = memFS.getWrittenPaths()
        const htmlFile = writtenPaths.find((p) => p.endsWith("index.html"))
        expect(htmlFile).toBeDefined()

        const content = memFS.getFileText(htmlFile!)
        expect(content).toBeDefined()
        expect(content).toContain("Hello, World!")
        expect(content).toContain("<!DOCTYPE html>")
    })

    it("should emit text delta events containing the confirmation message", async () => {
        const session = await agent.createSession()
        let fullText = ""

        for await (const event of agent.chat(
            session.id,
            "创建一个 hello world 的 HTML 页面",
        )) {
            if (event.type === "text_delta" && event.content) {
                fullText += event.content
            }
        }

        // The confirmation text from the LLM should appear in the streamed deltas
        expect(fullText).toContain("index.html")
    })
})
